---
- name: Install EPEL (CentOS)
  package:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS"

- name: Install EPEL (RHEL)
  package:
    name: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm
    state: present
  when: ansible_distribution == "EL"

- name: Install Wine
  package:
    name: wine
    state: present
